name: Test

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build with dotnet
      run: dotnet build

    - name: Run unit tests
      run: dotnet test --logger "console;verbosity=detailed";
