name: Resharper Code Analysis

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  resharper:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install resharper
        run: dotnet tool install -g JetBrains.ReSharper.GlobalTools
        
      - name: Run resharper inspection
        run: jb inspectcode Review-case.sln /output=insreport.xml

      - name: Run resharper duplicate code check
        run: jb dupfinder Review-case.sln /output=dupreport.xml

      - name: Check Reports
        run: powershell ./resharper.ps1
